# Generated by Django 2.1 on 2018-08-05 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedDateTime', models.DateTimeField(auto_now=True)),
                ('ModifiedDateTime', models.DateTimeField(auto_now_add=True)),
                ('ProjectName', models.CharField(max_length=50)),
                ('ProjectDescription', models.TextField()),
                ('ProjectImage', models.ImageField(upload_to='images/')),
                ('InstallDate', models.DateField()),
                ('TreatmentLength', models.FloatField()),
                ('TotalStructures', models.IntegerField()),
                ('ProjectAffiliation', models.CharField(max_length=60)),
                ('AffiliationImage', models.ImageField(upload_to='images/')),
                ('PrimaryContactName', models.CharField(max_length=60)),
                ('PrimaryContactEmail', models.EmailField(max_length=100)),
                ('CreatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
