# Generated by Django 2.1 on 2018-08-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='AffiliationImage',
            field=models.ImageField(upload_to='affiliation_images/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='ProjectImage',
            field=models.ImageField(upload_to='project_images/'),
        ),
    ]
