# Generated by Django 2.1 on 2018-08-11 23:24

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_projectcoordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='ProjectCoordinates',
        ),
        migrations.AddField(
            model_name='project',
            name='ProjectLocation',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
            preserve_default=False,
        ),
    ]
