# Generated by Django 2.1 on 2018-08-11 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20180811_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='ProjectLocation',
        ),
    ]
