# Generated by Django 2.1 on 2018-08-11 23:45

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_project_projectlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ProjectLocation',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
