# Generated by Django 2.1 on 2018-08-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20180813_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='BasinName',
            field=models.CharField(default='john day', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='StreamName',
            field=models.CharField(default='john day', max_length=50),
            preserve_default=False,
        ),
    ]
