# Generated by Django 2.1 on 2018-08-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20180815_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ProjectLatitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='ProjectLongitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
