# Generated by Django 2.1 on 2018-08-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20180815_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='AffiliationImage',
            field=models.ImageField(blank=True, null=True, upload_to='affiliation_images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='BasinName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='InstallDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='PrimaryContactEmail',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='PrimaryContactName',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='ProjectAffiliation',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='ProjectImage',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ProjectName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='StreamName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='TotalStructures',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='TreatmentLength',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
