# Generated by Django 2.1 on 2018-08-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20180815_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ProjectDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
