# Generated by Django 2.1 on 2018-09-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20180824_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='ProjectDescription',
            new_name='RestorationObjectives',
        ),
        migrations.AddField(
            model_name='project',
            name='StructureConstruction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
